In [5]:
import numpy as np

x = (np.tile(range(0,4), (8, 1)))

for i in range(x.shape[0]):
	np.random.shuffle(x[i].T)

# print(x)
y = np.tile(np.arange(0,4), 2)
np.random.shuffle(y)
# print(y)
# print('===================')

ref = x[range(x.shape[0]),y]

result1 = x - ref.reshape(8,1) + 1
print(result1)

print('===================')
result1 = np.maximum(result1, 0)
print(result1)

result1[result1 > 0] = 1
print(result1)
print(result1.shape)

# dW = X.T.dot(result1) * 1.0 / num_samples
# print(dW.shape)

# dW += reg * W * 2

[[ 3  4  2  1]
 [-1 -2  1  0]
 [ 1  0  2  3]
 [ 2  1  3  0]
 [-2 -1  0  1]
 [ 1 -2  0 -1]
 [ 0 -2  1 -1]
 [ 0  1 -1 -2]]
[[3 4 2 1]
 [0 0 1 0]
 [1 0 2 3]
 [2 1 3 0]
 [0 0 0 1]
 [1 0 0 0]
 [0 0 1 0]
 [0 1 0 0]]
[[1 1 1 1]
 [0 0 1 0]
 [1 0 1 1]
 [1 1 1 0]
 [0 0 0 1]
 [1 0 0 0]
 [0 0 1 0]
 [0 1 0 0]]
(8, 4)
